-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 14:30:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apnaMart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apnaMart` ;

-- -----------------------------------------------------
-- Schema apnaMart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apnaMart` DEFAULT CHARACTER SET utf8 ;
USE `apnaMart` ;

-- -----------------------------------------------------
-- Table `apnaMart`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Admin` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Admin` (
  `idAdmin` INT NOT NULL,
  `adminPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apnaMart`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Supplier` (
  `idSupplier` VARCHAR(45) NOT NULL,
  `S_name`CHAR(45) NOT NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  INDEX `fk_Supplier_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `apnaMart`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO Supplier(idSupplier,S_name,idAdmin)
VALUES
('S01', 'John', 1), ('S02', 'Jane', 1), ('S03', 'Michael', 1), ('S04', 'Emily', 1), ('S05', 'David', 1), ('S06', 'Sarah', 1), ('S07', 'William', 1), ('S08', 'Elizabeth', 1), ('S09', 'James', 1), ('S10', 'Ava', 1),
('S11', 'Alexander', 1), ('S12', 'Olivia', 1), ('S13', 'Daniel', 1), ('S14', 'Mia', 1), ('S15', ' Benjamin', 1), ('S16', 'Isabella', 1), ('S17', 'Matthew', 1), ('S18', 'Sophia', 1), ('S19', 'Jacob', 1), ('S20', 'Charlotte', 1),
('S21', 'Nicholas', 1), ('S22', 'Aria', 1), ('S23', 'Ryan', 1), ('S24', 'Abigail', 1), ('S25', 'Nathan', 1), ('S26', 'Ella', 1), ('S27', 'Jonathan', 1), ('S28', 'Avery', 1), ('S29', 'Ethan', 1), ('S30', 'Aaliyah', 1),
('S31', 'Samuel', 1), ('S32', 'Scarlett', 1), ('S33', 'Christopher', 1), ('S34', 'Adalynn', 1), ('S35', 'Henry', 1), ('S36', 'Audrey', 1), ('S37', 'Andrew', 1), ('S38', 'Hazel', 1), ('S39', 'Isaac', 1), ('S40', 'Violet', 1);


-- -----------------------------------------------------
-- Table `apnaMart`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Categories` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `nameCategories` VARCHAR(45) NOT NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idCategories`),
  INDEX `fk_Categories_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `apnaMart`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO Categories(nameCategories,idAdmin)
VALUES
('Clothing',001),
('Shoes',001),
('Accessories',001),
('Beauty and Personal Care',001),
('Home and Kitchen',001),
('Electronics',001),
('Sports',001),
('Toys and Games',001),
('Books',001),
('Grocery',001);


-- -----------------------------------------------------
-- Table `apnaMart`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Products` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Products` (
  `idProducts` VARCHAR(45) NOT NULL,
  `name`VARCHAR(45) NOT NULL,
  `idCategories` INT NOT NULL,
  `price` INT NOT NULL,
  `descript` VARCHAR(200) NULL,
  `quantity_available` INT NOT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Categories1_idx` (`idCategories` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`idCategories`)
    REFERENCES `apnaMart`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO Products(idProducts,name,idCategories,price,descript,quantity_available)
VALUES
('P01','T-Shirt',1, 500,'Black Cotton T-Shirt, Size M', 100),
('P02','Jeans',1,1500, 'Blue Denim Jeans, Size 32', 50),
('P03','Dress',1, 2000, 'Red Floral Printed Dress, Size L', 30),
('P04','Shirt',1, 1000, 'White Linen Shirt, Size XL', 40),
('P05','Skirt',1,800, 'Green A-Line Skirt, Size S', 60),
('P06','Blazer',1, 2500, 'Black Formal Blazer, Size M', 20),
('P07','Sweater',1, 1700, 'Gray Woolen Sweater, Size L', 35),
('P08','Jacket',1, 2000, 'Brown Leather Jacket, Size XL', 15),
('P09','Hoodie', 1,1200, 'Navy Blue Hoodie, Size M', 45),
('P10','Pants',1, 1200, 'Beige Chinos, Size 32', 50),
('P11','Nike',2, 3000, "Black and Red Running Shoes, Size 10", 30),
('P12','Adidas', 2,2500, "White and Blue Casual Shoes, Size 9", 40),
('P13','Puma',2, 2000, "Gray and Green Sneakers, Size 8", 50),
('P14','Reebok',2, 1500, "Red and Black Training Shoes, Size 7", 60),
('P15','Converse',2, 1700, "White and Black High-Top Sneakers, Size 10", 35),
('P16','Vans',2, 1900, "Black and White Skate Shoes, Size 9", 25),
('P17','New Balance',2, 2100, "Green and Gray Trail Running Shoes, Size 8", 20),
('P18','Skechers',2, 2000, "Black and White Walking Shoes, Size 7", 15),
('P19','Under Armour',2, 2500, "Black Basketball Shoes, Size 10", 10),
('P20','Brooks',2, 2800, "Blue and Orange Running Shoes, Size 9", 5),
('P21','Wallet',3, 800, "Brown Leather Bifold Wallet, Size M", 50),
('P22','Watch',3, 3000, "Black Stainless Steel Analog Watch, Unisex", 30),
('P23','Sunglasses',3, 1500, "Black Aviator Sunglasses, Unisex", 40),
('P24','Bag',3, 2000, "Brown Canvas Backpack, Size L", 20),
('P25','Scarf',3, 500, "Red and Black Plaid Scarf, Size M", 60),
('P26','Hat', 3,700, "Black Baseball Hat, One Size", 50),
('P27','Belt',3, 1000, "Brown Leather Belt, Size M", 45),
('P28','Gloves',3, 500, "Black Warm Winter Gloves, Size M", 35),
('P29','Umbrella', 3,700, "Black Compact Umbrella, One Size", 25),
('P30','Headphones', 3,1500, "Black Wireless Headphones, One Size", 15),
('P31','Perfume',4, 1500, "Ladies' Red Eau de Parfum, 50 ml", 30),
('P32','Lipstick', 4,700, "Matte Red Lipstick, Size M", 40),
('P33','Moisturizer',4,1200, "Men's Lightweight Moisturizer, 100 ml", 50),
('P34','Eyeliner', 4,800, "Black Liquid Eyeliner, Size S", 60),
('P35','Shampoo',4, 500, "Herbal Shampoo, 500 ml", 70),
('P36','Conditioner',4, 500, "Argan Oil Conditioner, 500 ml", 60),
('P37','Eyeshadow Palette',4, 2500, "Nude Eyeshadow Palette, Size M", 20),
('P38','Blush',4, 800, "Pink Powder Blush, Size S", 30),
('P39','Mascara', 4,900, "Waterproof Black Mascara, Size M", 40),
('P40','Nail Polish',4, 400, "Red Nail Polish, Size S", 50),
('P41','Microwave Oven',5, 5000, '20 litre capacity, multiple cooking options', 20),
('P42','Blender',5, 2000, '300W motor with stainless steel blades', 30),
('P43','Vacuum Cleaner',5, 7000, '1200W motor, bagless with HEPA filter', 15),
('P44','Toaster',5, 1500, '2 slice capacity with adjustable browning control', 40),
('P45','Gas Stove',5, 6000, '4 burners with automatic ignition', 25),
('P46','Iron',5, 1000, '2200W with steam function and adjustable temperature', 35),
('P47','Rice Cooker',5, 2500, '1.8 litre capacity with automatic shut-off', 50),
('P48','Sofa Cover',5, 1500, '3-seater size with machine washable fabric', 20),
('P49','Pillow',5, 500, '100% cotton cover with hypoallergenic filling', 80),
('P50','Cutlery Set',5, 3000, 'Stainless steel with 24 pieces including forks, knives, and spoons', 10),
('P51','Apple iPhone 12',6, 112799, '64GB, Space Grey, 5G Enabled', 100),
('P52','Samsung Galaxy S21',6, 34699, '128GB, Phantom Black, 5G Enabled', 150),
('P53','OnePlus 9 Pro',6, 15599, '256GB, Morning Mist, 5G Enabled', 200),
('P54','Xiaomi Mi 11',6, 14499,'128GB, Cosmic Black, 5G Enabled', 250),
('P55','Google Pixel 5',6, 36649, '128GB, Just Black, 5G Enabled', 200),
('P56','Sony Xperia 5 III',6, 17749, '256GB, Black, 5G Enabled', 150),
('P57','Realme Narzo 30 Pro',6, 18199, '64GB, White Knight, 4G Enabled', 300),
('P58','Honor 30S',6, 12249, '128GB, Magic Night Black, 5G Enabled', 200),
('P59','OPPO Find X3 Pro',6, 9999, '256GB, Gloss Black, 5G Enabled', 100),
('P60','Vivo X60 Pro',6, 59990, '128GB, Shimmer Blue, 5G Enabled', 150),
('P61','Basketball',7, 120, 'Size 7, Indoor/Outdoor Use', 500),
('P62','Tennis Racket',7, 375, 'Graphite, Lightweight, Strung', 200),
('P63','Running Shoes',7, 1120, "Men's size 9, Breathable Mesh", 300),
('P64','Yoga Mat',7,775, 'Non-Slip, Eco-Friendly, 72" x 24"', 400),
('P65','Jump Rope',7, 300, 'Adjustable Length, Foam Handles', 500),
('P66','Weightlifting Gloves',7, 899, 'Leather, Wrist Support, Non-Slip', 300),
('P67','Cycling Jersey', 7,1245, "Men's Large, Quick-Dry Fabric", 200),
('P68','Swimming Goggles',7, 999, "Anti-Fog, UV Protection, Adjustable Strap", 400),
('P69','Baseball Bat', 7,899, 'Aluminum, 31" Length, Youth Size', 300),
('P70','Hiking Backpack',7, 1599, '45L, Water Resistant, Adjustable Straps', 150),
('P71','Lego Set', 8,735, 'Star Wars Themed, 500 Pieces', 200),
('P72','Remote Control Car',8 ,699, '1:16 Scale, Off-Road', 300),
('P73','Stuffed Animal',8, 815, 'Cute and Soft, 12" Tall', 400),
('P74','Doll House',8, 599, 'Three Levels, Furnished', 100),
('P75','Action Figure',8, 200, 'Marvel Cinematic Universe, 6" Tall', 300),
('P76','Puzzle', 8,100, '1000 Piece, Landscape Scene', 200),
('P77','Board Game',8, 250, 'Monopoly Classic Edition', 150),
('P78','Play Tent',8, 499, 'Indoor/Outdoor Use, 45" x 45"', 200),
('P79','Building Blocks',8, 399, 'Large Set, 100 Pieces', 250),
('P80','Remote Control Helicopter',8, 1299, '2 Channel, Indoor Use', 100),
('P81',"Harry Potter and the Philosopher's Stone",9, 2000, 'Fantasy Fiction, Hardcover', 500),
('P82','To Kill a Mockingbird',9, 1599, 'Classics, Paperback', 400),
('P83','The Alchemist',9, 1200, 'Self-Discovery, Paperback', 300),
('P84','The Da Vinci Code',9, 1850, 'Mystery Thriller, Hardcover', 200),
('P85','The Lord of the Rings',9,2500, 'Fantasy Fiction, Hardcover', 200),
('P86','The Hunger Games',9, 2200, 'Science Fiction, Paperback', 250),
('P87','The Great Gatsby',9, 1500, 'Classics, Paperback', 300),
('P88','Pride and Prejudice',9, 1790, 'Classics, Paperback', 400),
('P89','1984',9, 1499, 'Dystopian Fiction, Paperback', 200),
('P90','Animal Farm',9, 120, 'Political Satire, Paperback', 300),
('P91','Rice',10, 100, 'Long Grain, 5lb bag', 300),
('P92','Pasta', 10,50, 'Penne, 1lb box', 400),
('P93','Bread', 10,30, 'Whole Wheat, Loaf', 500),
('P94','Sugar', 10,200, 'Granulated, 4lb bag', 400),
('P95','Cooking Oil',10, 700, 'Extra Virgin Olive Oil, 1L bottle', 200),
('P96','Tomatoes', 10,200, 'Ripe, Fresh, 1lb bag', 300),
('P97','Potatoes',10, 70, 'Russet, 5lb bag', 400),
('P98','Lemon',10, 100, 'Fresh, Medium-sized', 500),
('P99','Milk',10, 40, 'Whole, 1 gallon', 200),
('P100','Eggs',10, 60, 'Large, Grade A, Dozen', 300);



-- -----------------------------------------------------
-- Table `apnaMart`.`Inventory History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`InventoryHistory` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`InventoryHistory` (
  `S.No.` INT NOT NULL AUTO_INCREMENT,
  `idAdmin` INT NOT NULL,
  `idSupplier` VARCHAR(45) NOT NULL,
  `idProducts` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_Inventory_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  INDEX `fk_Inventory_Supplier1_idx` (`idSupplier` ASC) VISIBLE,
  INDEX `fk_Inventory_Products1_idx` (`idProducts` ASC) VISIBLE,
  PRIMARY KEY (`S.No.`),
  UNIQUE INDEX `S.No._UNIQUE` (`S.No.` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `apnaMart`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Inventory_Supplier1`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `apnaMart`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Inventory_Products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `apnaMart`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO InventoryHistory(idSupplier,idProducts,quantity,idAdmin)
VALUES
('S01','P01',100, 1),
('S01','P02',50, 1),
('S01','P03',30, 1),
('S02','P04',40, 1),
('S02','P05',60, 1),
('S02','P06',20, 1),
('S03','P07',35, 1),
('S03','P08',15, 1),
('S03','P09',45, 1),
('S04','P10',50, 1),
('S05','P11',30, 1),
('S05','P12',40, 1),
('S05','P13',50, 1),
('S06','P14',60, 1),
('S06','P15',35, 1),
('S06','P16',25, 1),
('S07','P17',20, 1),
('S07','P18',15, 1),
('S07','P19',10, 1),
('S08','P20',5, 1),
('S09','P21',50, 1),
('S09','P22',30, 1),
('S09','P23',40, 1),
('S10','P24',20, 1),
('S10','P25',60, 1),
('S10','P26',50, 1),
('S11','P27',45, 1),
('S11','P28',35, 1),
('S11','P29',25, 1),
('S12','P30',15, 1),
('S13','P31',30, 1),
('S13','P32',40, 1),
('S14','P33',50, 1),
('S14','P34',60, 1),
('S14','P35',70, 1),
('S15','P36',60, 1),
('S15','P37',20, 1),
('S16','P38',30, 1),
('S16','P39',40, 1),
('S16','P40',50, 1),
('S17','P41',20, 1),
('S17','P42',30, 1),
('S17','P43',40, 1),
('S18','P44',40, 1),
('S18','P45',50, 1),
('S18','P46',60, 1),
('S19','P47',70, 1),
('S19','P48',40, 1),
('S19','P49',49, 1),
('S20','P50',50, 1),
('S21','P51',51, 1),
('S22','P52',50, 1),
('S22','P53',300, 1),
('S22','P54',400, 1),
('S23','P55',50, 1),
('S23','P56',560, 1),
('S23','P57',70, 1),
('S24','P58',50, 1),
('S24','P59',5900, 1),
('S21','P60',6000, 1),
('S25','P61',6100, 1),
('S25','P62',6200, 1),
('S25','P63',6300, 1),
('S26','P64',6400, 1),
('S26','P65',6500, 1),
('S26','P66',6600, 1),
('S27','P67',6700, 1),
('S27','P68',6800, 1),
('S28','P69',60, 1),
('S28','P70',70, 1),
('S29','P71',100, 1),
('S29','P72',200, 1),
('S29','P73',300, 1),
('S30','P74',400, 1),
('S30','P75',500, 1),
('S30','P76',600, 1),
('S31','P77',700, 1),
('S31','P78',800, 1),
('S32','P79',700, 1),
('S32','P80',100, 1),
('S33','P81',100, 1),
('S33','P82',200, 1),
('S34','P83',300, 1),
('S34','P84',400, 1),
('S35','P85',500, 1),
('S35','P86',100, 1),
('S35','P87',50, 1),
('S36','P88',30, 1),
('S36','P89',40, 1),
('S36','P90',60, 1),
('S37','P91',20, 1),
('S37','P92',35, 1),
('S38','P93',15, 1),
('S38','P94',45, 1),
('S38','P95',50, 1),
('S39','P96',30, 1),
('S39','P97',40, 1),
('S39','P98',50, 1),
('S40','P99',60, 1),
('S40','P100',35, 1);




-- -----------------------------------------------------
-- Table `apnaMart`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Customer` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `first_name` CHAR(50) NOT NULL,
  `last_name` CHAR(50) NULL,
  `phno` VARCHAR(12) NOT NULL,
  `wallet` INT NULL,
  `street_address` VARCHAR(45) NOT NULL,
  `area_address` VARCHAR(45) NULL,
  `zip_address` CHAR(12) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;

INSERT INTO Customer(first_name,last_name,phno,wallet,street_address,area_address,zip_address,password)
VALUES
 ('Rosemonde', 'Brumpton', '241-525-4971', 10000, '91534 Dorton Crossing', 'Northview', '52125-536', 'eWa8P5'),
('Paulie', 'Haydon', '355-122-8796', 90000, '83 Randy Alley', 'Schmedeman', '76479-4403', 'D1hNW3AAvlP'),
 ('Lucretia', 'Vannini', '809-765-1458', 40000, '1 Longview Terrace', 'Bunting', '98132-123', 'S8hwVKVyk'),
 ('Erica', 'Garratt', '238-584-9757', 4000, '25 Bowman Road', 'Carey', '64942-1357', 'b2sQOSVcfq3'),
 ('Ricardo', 'Astupenas', '540-673-3723', 400, '189 Carey Center', 'Starling', '24208-313', 'anpWZOq'),
 ('Victor', 'Guisby', '780-739-9344', 5000, '7369 Miller Way', 'Green Ridge', '10812-914', '2YRBNUaVCH0m'),
 ('Carolee', 'Twinborough', '984-958-2119', 6000, '865 Artisan Avenue', 'Mariners Cove', '0409-9300', 'vvTsxpri'),
('Nikki', 'Turbitt', '711-955-3013', 200, '6 Haas Way', 'Goodland', '28595-420', 'bgF9LJ7x'),
('Sibylle', 'Yannoni', '323-949-0831', 100, '4118 Harbort Hill', 'Gina', '0536-5896', '7Gh8XeLXR3'),
('Mahala', 'Rimmer', '342-191-8526', 9999, '5055 Blaine Hill', 'Hagan', '68462-201', 'TMYvKRImo'),
('Alicea', 'Dell''Abbate', '872-344-6364', 7999, '7873 Rigney Court', 'Valley Edge', '50813-0008', 'YdPzb7lZ'),
 ('Ethelind', 'Commins', '243-228-8357',500, '759 Hansons Park', 'Thompson', '64942-1314', 'sszBLeMzy'),
 ('Federica', 'Woonton', '894-732-5532',200, '71 Arkansas Junction', 'Russell', '52959-876', 'A5u9vPWtN'),
('Brandon', 'Garcia', '548-423-7227', 900, '1 Cascade Place', 'Redwing', '65342-1010', 'g3b25b2Mo'),
('Calhoun', 'Brute', '372-795-1944', 300, '23 Derek Way', 'Lake View', '57344-028', 'pj9nyAcJQe'),
('Trace', 'Jennings', '807-576-4786',4000, '1598 Iowa Crossing', 'Reinke', '49288-0760', 'KKhFxb'),
('Elena', 'Vanshin', '586-916-8621',15000, '33031 Green Alley', 'Rutledge', '70253-106', 'rDWeuz4ynQiV'),
('Missie', 'Langmead', '938-446-8290',149, '45 Loftsgordon Way', 'Anthes', '64720-226', 'xXOnkv'),
 ('Ysabel', 'Kernoghan', '807-471-4316',2000, '5 Gateway Way', 'Dayton', '43345-003', 'AmuS7uvgyWc'),
 ('Selinda', 'Frears', '478-405-5546', 16000, '81910 Arapahoe Point', 'Melby', '58194-011', 'Hksgnww'),
 ('Reese', 'Bratt', '525-294-9080', 2999, '1607 Continental Junction', 'Pond', '0054-0056', 'gsQSc3iPK'),
 ('Mercy', 'O''Codihie', '778-382-4563', 7000, '3854 Sauthoff Hill', 'Mayer', '64942-0276', 'YbFNsJ'),
('Farleigh', 'Bordessa', '547-425-2838', 1000, '01671 Pepper Wood Parkway', 'Warner', '44911-0012', '38K7dIG'),
 ('Kris', 'Wytchard', '437-908-5198', 900, '95 Florence Road', 'Mifflin', '49349-197', 'W6Tw3f'),
('Sherlocke', 'Syddon', '690-173-4198',10000, '97302 Badeau Plaza', 'Packers', '53157-124', 'x8oSACTEyjIa'),
 ('Bancroft', 'Bigrigg', '236-453-3472', 600, '741 Farwell Junction', 'Raven', '13537-434', 'Zw1uGgXotQM'),
('Sheffy', 'Brookes', '763-111-9566',899, '63029 Warbler Trail', 'Florence', '37000-342', 'jBHVK4O11n7n'),
 ('Brien', 'Neiland', '602-864-8340',799, '59749 Drewry Alley', 'Arizona', '68387-166', 'n9rqBZp'),
 ('Rem', 'Elsmore', '349-114-7946',499, '4130 Toban Street', 'Westport', '47783-101', 'K78OL1pMxu2q'),
 ('Toby', 'Valente', '485-796-5866',10999, '07 Merrick Place', 'Loomis', '42549-542', 'Gvv1tda'),
('Del', 'Luberti', '364-466-4416',11999, '855 Esch Circle', 'Surrey', '63629-4072', 'JfNOHvaJwzYv'),
('Breena', 'Fliege', '267-753-6188',1200, '84 Kropf Lane', 'Longview', '43857-0138', 'dJoPNS'),
 ('Carlina', 'Annatt', '182-776-2922',1300, '33224 Mallory Park', '1st', '41250-000', 'F6mq7T5'),
('Otho', 'Funnell', '371-949-8638',1450, '0764 Gina Hill', 'Prairie Rose', '54575-358', 'fViOCjaYy9'),
('Cherlyn', 'Rupp', '600-287-2684', 900, '44 Walton Junction', 'Warbler', '52380-1721', 'rzdSIOITni3'),
('Brigida', 'O''Scandall', '972-879-0274',260, '164 Petterle Lane', 'Corben', '11716-0224', 'fKG5346Ofrz'),
('Timmie', 'Babinski', '906-966-1167',800, '5 Eagle Crest Pass', 'Golden Leaf', '49349-867', 'A9q9wDhlZVKf'),
('Clevey', 'Korbmaker', '635-854-1255',900, '91405 Kenwood Hill', 'Melody', '49371-015', 'p3DAEPDo'),
('Brennan', 'Iamittii', '168-398-1665',100, '51648 Roxbury Parkway', 'Melody', '0085-4353', 't3iO5hSn'),
('Rafaello', 'Bockmaster', '245-471-3100',150, '29 Carberry Court', 'Shoshone', '63323-013', 'd6jJayR'),
('Vinnie', 'Lavarack', '273-481-4917',390, '0114 Lyons Plaza', 'Jenna', '55910-411', '3kx8OauTzf'),
 ('Etti', 'Valente', '939-291-1956', 1400, '50126 Basil Plaza', 'Debra', '52584-301', 'pGCPmNRVMM'),
('Dayna', 'Carlesi', '658-952-3650',14999, '10671 Shoshone Terrace', 'Mandrake', '64175-991', 'lIVkNjbry6'),
('Kari', 'Pechacek', '641-864-3583',15999, '261 Dixon Court', 'Michigan', '41250-880', 'ukBlnvEMlg3'),
('Drusie', 'Lanchbery', '956-356-3980',1000, '6 Schiller Alley', 'Birchwood', '49781-062', 'FJXi6Rx6fQ2'),
('Jamison', 'Vannacci', '904-192-7999',20000, '95973 Waywood Alley', 'Anzinger', '68084-221', 'xBEchH'),
('Kath', 'Kerford', '904-658-4911',30000, '6854 Butterfield Lane', 'Clemons', '0573-0154', 'E0tvLGs4Me'),
('Emmye', 'Michelmore', '410-770-0086', 6000, '0 Birchwood Crossing', 'Kensington', '11410-011', 'gaPKjbb1QHei'),
('Robbie', 'Fyrth', '491-678-8613',5000, '1993 Village Terrace', 'Dottie', '43498-109', '8yShu5J'),
('Norrie', 'Huniwall', '655-799-7148',550, '2 Declaration Avenue', 'Emmet', '50114-4500', 'pfXSRC'),
('Clemence', 'Whitford', '443-160-8781',2678, '19545 Redwing Drive', 'Northwestern', '42507-807', 'OhG5IKuBcT0'),
('Kelwin', 'Jewar', '184-477-0046', 890, '3 Merchant Avenue', 'Amoth', '68196-224', 'G5MtAzAl19'),
('Eula', 'Truin', '517-599-6799',560, '2897 Arizona Center', 'Aberg', '43063-190', 'YcsfqxCXAP'),
('Pyotr', 'Bliven', '166-553-9562',30000, '0 Pierstorff Trail', 'Kennedy', '64942-1270', 'OjkUKnXiQ'),
('Sybil', 'Crippell', '561-969-3606',3000, '4 Dunning Circle', 'South', '57451-5026', 'Kti3mLMES'),
('Caritta', 'Fateley', '431-528-7012',999, '53 Luster Trail', 'Kinsman', '68428-120', 'fIwrkI1xZ0ZX'),
('Aurora', 'Bompas', '162-104-9090',7890, '703 Westend Hill', 'Bay', '65121-010', 'H2BekSj2'),
('Sibylla', 'Bankhurst', '569-957-9896',3450, '47571 Fairview Road', 'Hayes', '46123-013', 'FqzTRLzU'),
('Clarabelle', 'Longridge', '599-677-4079',5000, '1792 Service Crossing', 'Dennis', '10742-6761', 'iLm85q'),
('Syd', 'Baldazzi', '730-184-4858', 6000, '055 Rusk Place', 'Mcguire', '55319-225', 'Po2TFMJi'),
('Laurie', 'Lippiett', '762-588-2901',8999, '769 Knutson Street', 'Scofield', '61328-002', 'LySJ4M'),
('Andriette', 'Amner', '263-992-6979', 9000, '65 Mandrake Center', 'Valley Edge', '62584-974', 'p7I1kV3NPd'),
('Harlan', 'Attock', '209-957-9762',19000, '6145 Roxbury Lane', 'Mariners Cove', '46708-112', 'F1lb1O1'),
('Minerva', 'Venables', '752-275-8588',20000, '78 Lerdahl Pass', 'Schlimgen', '58809-350', 'FaQxUDdH'),
('Dwain', 'Blain', '764-407-2827', 7900, '2 Clyde Gallagher Pass', 'Lakewood Gardens', '0409-7938', 'w4YRnv'),
('Anthia', 'Brake', '509-964-4235',8999, '7 Eastlawn Crossing', 'Trailsway', '60660-7781', 'iyAaVaJie5c0'),
('Phillida', 'Alwen', '136-798-4177',1200, '89 Pleasure Alley', 'Elka', '55312-660', 'yaFdXGI0kI'),
('Lorena', 'Enrigo', '768-718-1435',6000, '8392 Buell Way', 'Redwing', '76420-372', 'IKF3Wo7'),
 ('Harold', 'Sangra', '821-659-3117',189, '4 Westport Plaza', 'Oak', '65862-162', '7u2wnqTEpw'),
('Lois', 'Van Waadenburg', '528-583-3855',230, '3 Del Sol Street', 'Briar Crest', '49288-0753', 'YgfBa2m4B'),
('Guthrey', 'Bummfrey', '392-988-3022',455, '036 Straubel Court', 'Fallview', '67046-641', 'vbp4Vct9QY'),
('Nissie', 'Duncklee', '727-897-2372',600, '18 Bunting Center', 'Armistice', '0143-9716', 'I5nBsOWF0'),
('Terrill', 'Kubacek', '702-132-7958',800, '9534 Dryden Lane', 'Lunder', '64720-123', 'sZn5gD3Z'),
('Averill', 'Vigne', '740-595-9156',900, '74 Farwell Plaza', 'Meadow Ridge', '0904-6302', 'NEMT0x'),
('Mead', 'Pershouse', '769-857-0916',1400, '27 Sherman Parkway', 'Corben', '68745-1069', '8aAyBbA'),
('Rozamond', 'Oganesian', '194-896-0551',3000, '066 Eagle Crest Road', 'Birchwood', '0536-1021', '4ZwFEF7ebY63'),
('Jedd', 'Scade', '387-421-0753',6000, '0004 Tony Center', 'International', '43063-213', 'nhMGKfTtG'),
('Mil', 'Thickpenny', '350-110-5824',800, '82 Kedzie Center', 'Drewry', '0093-3109', 'ASPX4G'),
('D''arcy', 'Priddy', '879-305-4206',9000, '82022 Arrowood Center', 'Commercial', '65517-1008', 'rft9Qf'),
('Tiffie', 'Grindle', '949-822-2547',7000, '086 Elgar Way', 'Delladonna', '69226-010', 'YYACZyEK1'),
('Fania', 'Urwin', '513-609-0298',670, '9 John Wall Court', 'Pleasure', '67046-157', 'IlDL1y2x'),
('Avrom', 'Illingworth', '402-273-8920',1444, '0747 Fulton Avenue', 'Lindbergh', '59572-425', 'dW4zpmSArSL'),
('Terri', 'Doers', '515-519-7189', 18000, '96 Little Fleur Way', 'Kropf', '0615-7708', '36o6N3LJAXv'),
('Cesya', 'Patchett', '571-754-0178', 10, '24 Ronald Regan Pass', 'Del Mar', '43314-001', 'HTJMLr'),
 ('Angelica', 'Curror', '710-285-0332',70, '2495 Anhalt Pass', 'Burrows', '0378-2821', 'EYrkYk'),
('Rodd', 'Durran', '165-293-8040',788, '309 Coolidge Alley', 'Morrow', '49999-192', 'b0Mt8NrfIgn'),
('Franklin', 'Subhan', '204-642-0258',800, '12 Schiller Place', 'Amoth', '55154-8297', '4fge35CYeSiy'),
('Heath', 'Litterick', '287-140-8196',600, '22203 Doe Crossing Center', 'Farmco', '55289-463', 'MfzT51'),
('Adria', 'Goney', '916-813-5032', 800, '4 Brickson Park Crossing', 'Arrowood', '67877-305', 'qTCT4n'),
('Laurice', 'Cabble', '830-450-9197',900, '069 Clove Hill', 'Golf Course', '52125-123', 'JZlNYkc'),
('Sella', 'Sibylla', '360-415-6239',700, '1 Morningstar Plaza', 'Vahlen', '37808-061', '0HZXDbM'),
('Sunny', 'Ros', '626-370-4521', 19000, '53421 Little Fleur Lane', 'Ludington', '0944-8402', 'BNga1w'),
 ('Daffie', 'Loachhead', '234-332-7567',17000, '53261 Crownhardt Hill', 'Kensington', '64990-605', 'rgIreET'),
 ('Isador', 'Nutkins', '510-254-7518',700, '93098 Blue Bill Park Way', 'Elgar', '64064-050', 'eBqMbf'),
('Brannon', 'Keller', '107-261-8116',800, '7 Toban Pass', 'Rigney', '69004-002', '95vuk91'),
('Willdon', 'Cowie', '479-188-6333',80, '2808 Straubel Parkway', 'Blue Bill Park', '21749-540', '6Aw2SGT6d7vM'),
('Maribel', 'Thompstone', '848-752-6843',90, '7 Jay Court', 'Schlimgen', '68180-844', '975ZMKg'),
 ('Cassius', 'Craddock', '210-638-4680',20, '01 Shopko Crossing', 'Sunbrook', '36987-1103', 'TxUSyaZHi88'),
 ('Adrienne', 'Tallon', '906-870-7193', 80, '9 Hovde Trail', 'Holmberg', '51824-011', 'pfSZ61cd9WO'),
 ('Durante', 'Stearn', '590-882-8066', 10000, '3 Cambridge Alley', 'Kensington', '37205-539', 'yNp15Q9F7');



-- -----------------------------------------------------
-- Table `apnaMart`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnamart`.`cart` ;

CREATE TABLE IF NOT EXISTS `apnamart`.`cart` (
  `idCustomer` INT NOT NULL,
  `idProducts` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  INDEX `fk_Carts_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_Carts_Products1_idx` (`idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Carts_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `apnamart`.`customer` (`idCustomer`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Carts_Products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `apnamart`.`products` (`idProducts`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO cart(idCustomer,idProducts,quantity)
VALUES
(1,NULL,NULL), (2,NULL,NULL), (3,NULL,NULL), (4,NULL,NULL), (5,NULL,NULL), (6,NULL,NULL), (7,NULL,NULL), (8,NULL,NULL), (9,NULL,NULL), (10,NULL,NULL),
(11,NULL,NULL), (12,NULL,NULL), (13,NULL,NULL), (14,NULL,NULL), (15,NULL,NULL), (16,NULL,NULL), (17,NULL,NULL), (18,NULL,NULL), (19,'P08',2), (20,'P29',5),
(21,'P97',8), (22,'P03',1), (23,'P13',3), (24,NULL,NULL), (25,NULL,NULL), (26,'P13',5), (27,NULL,NULL), (28,NULL,NULL), (29,NULL,NULL), (30,'P56',2),
(31,NULL,NULL), (32,NULL,NULL), (33,NULL,NULL), (34,NULL,NULL), (35,'P97',2), (36,NULL,NULL), (37,NULL,NULL), (38,NULL,NULL), (38,NULL,NULL), (39,NULL,NULL),
(40,NULL,NULL), (41,NULL,NULL), (42,NULL,NULL), (43,'P34',1), (44,NULL,NULL), (45,NULL,NULL), (46,NULL,NULL), (47,NULL,NULL), (48,NULL,NULL), (49,NULL,NULL),
(50,NULL,NULL), (51,NULL,NULL), (52,NULL,NULL), (52,NULL,NULL), (53,NULL,NULL), (54,NULL,NULL), (55,'P27',2), (56,NULL,NULL), (57,NULL,NULL), (58,NULL,NULL),
(59,NULL,NULL), (60,NULL,NULL), (61,NULL,NULL), (62,NULL,NULL), (63,NULL,NULL), (64,NULL,NULL), (65,NULL,NULL), (66,NULL,NULL), (67,NULL,NULL), (68,NULL,NULL),
(69,NULL,NULL), (70,'P67',4), (71,NULL,NULL), (72,NULL,NULL), (73,NULL,NULL), (74,NULL,NULL), (75,NULL,NULL), (76,NULL,NULL), (77,NULL,NULL), (78,NULL,NULL),
(79,NULL,NULL), (80,NULL,NULL), (81,NULL,NULL), (82,NULL,NULL), (83,NULL,NULL), (84,NULL,NULL), (85,NULL,NULL), (86,NULL,NULL), (87,NULL,NULL), (88,NULL,NULL),
(89,NULL,NULL), (90,NULL,NULL), (91,NULL,NULL), (92,NULL,NULL), (93,'P24',2), (94,NULL,NULL), (95,NULL,NULL), (96,NULL,NULL), (97,NULL,NULL), (98,NULL,NULL), (99,NULL,NULL), (100,NULL,NULL);






-- -----------------------------------------------------
-- Table `apnaMart`.`Vouchers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Vouchers` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Vouchers` (
  `idvoucher` INT NOT NULL,
  `discount` INT(100) NOT NULL,
  `expiry_date` datetime NOT NULL,
  `idCustomer` INT NOT NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idvoucher`),
  INDEX `fk_Vouchers_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_Vouchers_Admin1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Vouchers_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `apnaMart`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Vouchers_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `apnaMart`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO Vouchers(idvoucher,discount,expiry_date,idAdmin,idCustomer)
 VALUES
(492, 10, '2023-05-03',1,15),
(738, 20, '2023-02-08',1,26),
(685, 25, '2023-12-31',1,28),
(301, 5, '2023-04-17',1,37),
(654, 15, '2023-10-12',1,12),
(823, 35, '2023-11-02',1,84),
(523, 30, '2023-06-15',1,40),
(657, 25, '2023-09-28',1,49),
(798, 10, '2023-06-01',1,1),
(411, 15, '2023-02-14',1,67),
(680, 20, '2023-07-16',1,79),
(719, 25, '2023-12-25',1,99);


-- -----------------------------------------------------
-- Table `apnamart`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnamart`.`orders` ;

CREATE TABLE IF NOT EXISTS `apnamart`.`orders` (
  `idOrders` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  `totalAmount` INT NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  `dateDelivery` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_orders_customer1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `apnamart`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;
INSERT INTO Orders(idOrders,totalAmount,idCustomer,OrderDate,dateDelivery)
VALUES
(13870,  8977,23,'2023-08-02','2023-08-09'),
(15612, 5756,22,'2023-01-17','2023-01-19'),
(14258,  6798,30,'2023-01-18','2023-01-28'),
(12897,  9234,43,'2023-02-01','2023-02-11'),
(15321,  7523,70,'2023-02-08','2023-02-13'),
(15900,  8634,93,'2023-02-11','2023-02-17'),
(13471,  9456,55,'2023-02-17','2023-02-24'),
(16000,  7987,26,'2023-02-21','2023-02-26'),
(14502, 6458,19,'2023-02-25','2023-02-28'),
(12690, 8702,20,'2023-02-28','2023-03-04'),
(15913, 5678,21,'2023-01-05','2023-01-09'),
(14278,7901,35,'2023-01-13','2023-01-19');



-- -----------------------------------------------------
-- Table `apnaMart`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`Payment` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`Payment` (
  `date` DATETIME NULL,
  `idOrders` INT NOT NULL,
  INDEX `fk_Payment_Orders1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `apnaMart`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO Payment(date,idOrders)
VALUES

('2023-08-02 12:34:23',15900),
('2023-01-05 13:56:12',15913),
('2023-08-02 14:12:01',13870),
('2023-01-17 15:23:45',15612),
('2023-01-28 16:45:23',14258),
('2023-02-11 17:12:34',12897),
('2023-02-13 18:34:12',15321),
('2023-02-17 19:12:23',13471),
('2023-02-26 20:45:12',16000),
('2023-02-25 21:34:23',14502),
('2023-02-28 22:12:01',12690),
('2023-01-13 23:45:23',14278);


-- -----------------------------------------------------
-- Table `apnaMart`.`Order Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`OrderStatus` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`OrderStatus` (
  `Shipped` BIT(1) NOT NULL,
  `OutForDelivery` BIT(1) NOT NULL,
  `Delivered` BIT(1) NOT NULL,
  `idOrders` INT NOT NULL,
  INDEX `fk_Order Status_Orders1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_Order Status_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `apnaMart`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO OrderStatus(Shipped,OutForDelivery,Delivered,idOrders)
VALUES
(1,1,0,13870),
(1,0,0,15612),
(1,0,0,14258),
(0,0,0,12897),
(0,0,0,15321),
(1,1,1,15900),
(1,1,0,13471),
(1,0,0,16000),
(0,0,0,14502),
(0,0,0,12690),
(1,1,1,15913),
(1,1,0,14278);


-- -----------------------------------------------------
-- Table `apnaMart`.`orderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`orderDetails` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`orderDetails` (
  `idProducts` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `idOrders` INT NOT NULL,
  INDEX `fk_cartDetails_Products1_idx` (`idProducts` ASC) VISIBLE,
  INDEX `fk_orderDetails_Orders1_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `fk_cartDetails_Products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `apnaMart`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orderDetails_Orders1`
    FOREIGN KEY (`idOrders`)
    REFERENCES `apnaMart`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO orderDetails(idProducts,quantity,idOrders)
VALUES
('P09',5,14278),
('P14',2,15913),
('P56',1,12690),
('P23',1,14502),
('P23',3,16000),
('P56',1,13471),
('P09',5,15900),
('P09',5,15321),
('P55',5,12897),
('P99',2,14258),
('P09',5,15612),
('P19',2,13870);



-- -----------------------------------------------------
-- Table `apnaMart`.`Voucher Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apnaMart`.`VoucherStatus` ;

CREATE TABLE IF NOT EXISTS `apnaMart`.`VoucherStatus` (
  `dateIssued` DATETIME NOT NULL,
  `used` BIT(1) NOT NULL,
  `dateUsed` DATETIME NULL,
  `idvoucher` INT NOT NULL,
  INDEX `fk_Voucher Status_voucher1_idx` (`idvoucher` ASC) VISIBLE,
  CONSTRAINT `fk_Voucher Status_voucher1`
    FOREIGN KEY (`idvoucher`)
    REFERENCES `apnaMart`.`Vouchers` (`idvoucher`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;
INSERT INTO VoucherStatus(dateIssued,used,dateUsed,idvoucher)
VALUES
('2022/08/22 ,4:00:00', 0, '2022/12/26 ,12:00:00',492),
('2022/11/06 ,10:00:00', 1, NULL,738),
('2022/05/22 ,9:00:00', 0,'2022/10/29 ,7:00:00',685),
('2022/01/15 ,7:30:00', 1, NULL,301),
('2022/04/05 ,11:50:00', 1, NULL,654),
('2022/12/13 ,6:00:50', 1, NULL,823),
('2022/6/16 ,5:30:00', 0, '2022/11/05 ,10:00:00',523),
('2022/02/01,7:00:00', 1, NULL,657),
('2022/11/19 ,4:00:00', 1, NULL,798),
('2022/06/12 ,9:40:00', 1,NULL,411),
('2022/10/02 ,12:50:00', 1, NULL,680),
('2022/01/24 ,3:50:00', 0, '2022/08/21 ,4:00:00',719);




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
